### ISSUE TITLE
v2 plugin spec should have a constant name

### ISSUE THREAD

**Issue by harsimranmaan** [kf5i/k3ai-plugins#37]
**Is your feature request related to a problem? Please describe.**
The v2 spec uses plugin definitions of the form v2/argo/argo.yaml. The plugin spec file name should be independent of the plugin name. This would make tooling more convention driven and handling of different naming formats of plugin names would be easier.

I am proposing something like `v2/argo/k3ai_plugin.yaml` but something as simple as `v2/argo/plugin.yaml` should suffice.

**Comment by Gsantomaggio** [comment]
The idea is to have more files inside the directory. 
[Here](https://github.com/kf5i/k3ai-core/blob/main/internal/plugins/manage.go#L71-L77) we load all the files  ignoring the name

**Comment by Gsantomaggio** [comment]
Btw I agree with a naming convention. We need to filter only the `plugins` types 
so we will manage all the files that start with plugin as `v2/argo/plugin*.yaml`

**Comment by Gsantomaggio** [comment]
I ended up to have only one file, as suggested on the [issue](https://github.com/kf5i/k3ai-plugins/issues/37#issue-728556058)
